### ISSUE TITLE
Redução de requisitos

### ISSUE THREAD

**Issue by lecneri** [dancosbr/cpf-cnpj-bundle#1]
Olá,
Você está usando alguma feature do PHP 8.2 para usar ele como requerimento? Se não teria como diminuir o requerimento do PHP 8.2?

**Comment by danielcosta** [comment]
Olá @lecneri,

Qual versão do php seria ideal pro seu cenário? Podemos avaliar aqui de baixar o requisito sem problemas...

**Comment by lecneri** [comment]
Eu estou trabalhando com a versão 8.1 do PHP, mas se você estiver usando [SensitiveParameter](https://www.php.net/manual/en/class.sensitiveparameter.php) por se tratar de item protegido pela LGPD não precisa reduzir os requisitos.

**Comment by danielcosta** [comment]
@lecneri estou em viagem essa semana e vou conseguir trabalhar nessa issue e no seu PR apenas na próxima semana.

**Comment by danielcosta** [comment]
Olá, foi publicada a [v1.1.0](https://packagist.org/packages/dancos/cpf-cnpj-bundle#v1.1.0) com o mesmo codebase mas que aceita PHP 8.1 como versão mínima.

Na sequencia irei publicar uma nova major aumentando a mínima requerida do PHP pra 8.2 novamente e após isso poderei aceitar o PR #2 que você mandou.

Obrigado pela contribuição!
